version: 0.2

phases:
  install:
    commands:
      - echo "Starting dependency installation for backend"
      - cd backend
      - npm install
      - echo "Backend dependencies installed"

      - echo "Starting dependency installation for frontend"
      - cd ../frontend
      - npm install
      - echo "Frontend dependencies installed"

  build:
    commands:
      - echo "Building frontend"
      - npm run build

      # If you need to copy the frontend build to the backend directory
      - echo "Moving frontend build files to backend public directory"
      - cp -r build ../backend/public

      - echo "Build and setup complete"
