version: 0.2

phases:
  install:
    commands:
      - echo "Starting backend and frontend installation"
      - cd backend
      - npm install
      - echo "Backend dependencies installed"
      - cd ../frontend
      - npm install
      - echo "Frontend dependencies installed"
  pre_build:
    commands:
      - echo "Pre-build phase completed"
  build:
    commands:
      - echo "Building frontend"
      - cd ../frontend
      - npm run build
      - echo "Frontend build complete"
      - cd ../backend
      - echo "Backend setup is ready"
  post_build:
    commands:
      - echo "Build and setup complete"
