version: 0.2

phases:
  install:
    commands:
      - echo "Installing backend dependencies"
      - cd backend
      - rm -rf node_modules # Clear node_modules to ensure a fresh install
      - npm install
      - echo "Backend dependencies installed"

      - cd ..
      - echo "Installing frontend dependencies"
      - cd frontend
      - rm -rf node_modules # Clear node_modules to ensure a fresh install
      - npm install
      - echo "Frontend dependencies installed"

      # Verify that react-scripts is installed
      - echo "Checking if react-scripts is installed in frontend"
      - if [ ! -f node_modules/.bin/react-scripts ]; then echo "react-scripts is missing. Re-installing frontend dependencies"; rm -rf node_modules; npm install; fi

  build:
    commands:
      - echo "Building frontend"
      - npm run build

      # Copy frontend build files to backend public folder (if needed)
      - echo "Copying frontend build to backend public folder"
      - cp -r build ../backend/public
      - echo "Build and setup complete"

artifacts:
  files:
    - backend/**/* # Include everything in the backend folder
  base-directory: backend # Base directory for artifacts
  discard-paths: no # Preserve directory structure
