version: 0.2

phases:
  install:
    commands:
      - echo "Starting backend and frontend installation"
      - cd backend
      - npm install
      - echo "Backend dependencies installed"
      - cd ../frontend
      - npm install
      - echo "Frontend dependencies installed"
      - ls -la node_modules/.bin # List .bin directory to confirm react-scripts is installed
  pre_build:
    commands:
      - echo "Pre-build phase completed"
  build:
    commands:
      - echo "Building frontend"
      - cd ../frontend
      - ls -la # List all files to confirm presence of node_modules and required files
      - npm run build
      - echo "Frontend build complete"
      - cd ../backend
      - echo "Backend setup is ready"
  post_build:
    commands:
      - echo "Build and setup complete"
