AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to set up a single EC2 instance for Afriqana app.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro # Free tier eligible
      ImageId: ami-04b54ebf295fe01d7 # Amazon Linux 2 AMI
      KeyName: AfriqanaKeyPair # Replace with your key pair name
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          echo "Welcome to Afriqana!" > /var/www/html/index.html
      Tags:
        - Key: name
          Value: Afriqana # will match the name tag used in codedeploy

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allow SSH access from anywhere (optional, could restrict to your IP)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allow HTTP access from anywhere

Outputs:
  EC2PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
